# Generated by Django 2.2 on 2019-12-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oasis',
            options={'ordering': ['-id']},
        ),
    ]
