# Generated by Django 2.2 on 2019-12-17 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_oasis_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='oasis',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='oasisLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('oasis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.oasis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='oasis',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='oasis_user', through='posts.oasisLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
